# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=14, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=165, null=True)),
                ('direccion', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('iva', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=14, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=165, null=True)),
                ('direccion', models.TextField(blank=True, max_length=400, null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('iva', models.FloatField(blank=True, null=True)),
                ('ir', models.FloatField(blank=True, null=True)),
                ('al', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Cliente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('precio', models.FloatField(null=True)),
                ('costo', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Factura'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Producto'),
        ),
    ]
