# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name=b'nombre de la empresa')),
                ('numero_ruc', models.CharField(max_length=14, verbose_name=b'registro unico del contribuidor (RUC)')),
                ('direccion', models.CharField(max_length=255, verbose_name=b'direccion de la empresa')),
                ('telefono', models.CharField(max_length=14, verbose_name=b'numero de telefono')),
                ('email', models.CharField(max_length=255, verbose_name=b'correo electronico')),
                ('web', models.CharField(max_length=14, verbose_name=b'sitio web')),
            ],
        ),
    ]
