# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'ruc/cedula')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('tipo_relacion', models.CharField(choices=[(b'CL', b'CLIENTE'), (b'PR', b'PROVEEDOR')], default=b'CL', max_length=2, verbose_name=b'tipo de relacion')),
                ('tiempo_entrega', models.PositiveIntegerField(default=0, help_text=b'tiempo de entrega en dias para la mercaderia', null=True, verbose_name=b'tiempo de entrega')),
                ('limite_credito', models.FloatField(blank=True, default=0, null=True, verbose_name=b'limite de credito')),
                ('saldo', models.FloatField(blank=True, default=0, verbose_name=b'saldo inicial')),
                ('plazo', models.PositiveIntegerField(default=0, help_text=b'plazo de credito expresado en cantidad de dias', null=True)),
            ],
            options={
                'db_table': 'prueba_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencias', models.FloatField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'ruc/cedula')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('tipo_relacion', models.CharField(choices=[(b'CL', b'CLIENTE'), (b'PR', b'PROVEEDOR')], default=b'CL', max_length=2, verbose_name=b'tipo de relacion')),
                ('tiempo_entrega', models.PositiveIntegerField(default=0, help_text=b'tiempo de entrega en dias para la mercaderia', null=True, verbose_name=b'tiempo de entrega')),
                ('limite_credito', models.FloatField(blank=True, default=0, null=True, verbose_name=b'limite de credito')),
                ('saldo', models.FloatField(blank=True, default=0, verbose_name=b'saldo inicial')),
                ('plazo', models.PositiveIntegerField(default=0, help_text=b'plazo de credito expresado en cantidad de dias', null=True)),
            ],
            options={
                'db_table': 'prueba_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='total_periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_pagado', models.FloatField(default=0)),
                ('iva_contra', models.FloatField(default=0)),
                ('ir_cobrado', models.FloatField(default=0)),
                ('ir_pagado', models.FloatField(default=0)),
                ('al_recaudado', models.FloatField(default=0)),
                ('al_pagado', models.FloatField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycash.Categoria')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('saldo', models.FloatField(default=0, help_text=b'saldo actual de la cuenta')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_madre', to='moneycash.Cuenta')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='cuenta_periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial', models.FloatField(default=0)),
                ('saldo_final', models.FloatField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.Cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'ruc/cedula')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('fecha_vence', models.DateField(blank=True, help_text=b'si se deja en blanco se aplica el plazo del provedor', null=True, verbose_name=b'fecha de vencimiento')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('autorizado', models.BooleanField(default=True)),
                ('impreso', models.BooleanField(default=False)),
                ('contabilizado', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(choices=[(b'CO', b'CONTADO'), (b'CR', b'CREDITO')], default=b'CO', max_length=2, verbose_name=b'forma de pago')),
                ('subtotal', models.FloatField(default=0.0)),
                ('descuento', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.0)),
                ('exento_iva', models.BooleanField(default=False)),
                ('x_iva', models.FloatField(blank=True, default=100)),
                ('ir', models.FloatField(default=0.0, verbose_name=b'retencion del ir')),
                ('exento_ir', models.BooleanField(default=False)),
                ('x_ir', models.FloatField(blank=True, default=100)),
                ('al', models.FloatField(default=0.0, verbose_name=b'retencion de la alcaldia')),
                ('exento_al', models.BooleanField(default=False, verbose_name=b'exento alcaldia')),
                ('x_al', models.FloatField(blank=True, default=100)),
                ('total', models.FloatField(default=0.0)),
                ('abonado', models.FloatField(default=0.0)),
                ('saldo', models.FloatField(default=0.0)),
                ('tc', models.FloatField(default=1.0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('existencias', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('comprar', models.BooleanField(default=True)),
                ('vender', models.BooleanField(default=True)),
                ('almacenar', models.BooleanField(default=True)),
                ('factor', models.FloatField(default=2)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycash.Categoria')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.FloatField(default=1)),
                ('existencias', models.FloatField(default=0)),
                ('saldo', models.FloatField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('costo_entrada', models.FloatField(default=0)),
                ('costo_anterior', models.FloatField(default=0)),
                ('costo_promedio', models.FloatField(default=0)),
                ('costo_importacion', models.FloatField(default=0)),
                ('costo_internacion', models.FloatField(default=0)),
                ('recibido', models.FloatField(blank=True, null=True)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycash.Bodega')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycash.Documento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.FloatField(default=0)),
                ('haber', models.FloatField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.Cuenta')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.Documento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Numeracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('inicio_produccion', models.DateField(blank=True, null=True)),
                ('fin_produccion', models.DateField(blank=True, null=True)),
                ('inicio_ventas', models.DateField(blank=True, null=True)),
                ('fin_ventas', models.DateField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_final'],
            },
        ),
        migrations.CreateModel(
            name='relacion_comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[(b'CL', b'CLIENTE'), (b'PR', b'PROVEEDOR')], default=b'CL', max_length=2, verbose_name=b'tipo de relacion')),
                ('tiempo_entrega', models.PositiveIntegerField(default=0, help_text=b'tiempo de entrega en dias para la mercaderia', null=True, verbose_name=b'tiempo de entrega')),
                ('limite_credito', models.FloatField(blank=True, default=0, null=True, verbose_name=b'limite de credito')),
                ('saldo', models.FloatField(blank=True, default=0, verbose_name=b'saldo inicial')),
                ('plazo', models.PositiveIntegerField(default=0, help_text=b'plazo de credito expresado en cantidad de dias', null=True)),
            ],
            options={
                'verbose_name': 'relacion comercial',
                'verbose_name_plural': 'relaciones comerciales',
            },
        ),
        migrations.CreateModel(
            name='SocioComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'ruc/cedula')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'socios comerciales',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Tc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('oficial', models.FloatField()),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moneycash.Moneda')),
            ],
            options={
                'verbose_name': 'tasa de cambio',
                'verbose_name_plural': 'tasas de cambio',
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'codigo')),
                ('name', models.CharField(max_length=100, verbose_name=b'nombre')),
                ('activo', models.BooleanField(default=True)),
                ('contabiliza', models.BooleanField(default=True, help_text=b'indica si el documento tiene afectacion contable')),
                ('afectacion', models.IntegerField(choices=[(1, b'POSITIVA'), (-1, b'NEGATIVA'), (0, b'SIN AFECTACION')], help_text=b'tipo de afectacion inventarial')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documentos',
            },
        ),
        migrations.AddField(
            model_name='relacion_comercial',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.SocioComercial'),
        ),
        migrations.AddField(
            model_name='numeracion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.Sucursal'),
        ),
        migrations.AddField(
            model_name='numeracion',
            name='tipodoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.TipoDoc'),
        ),
        migrations.AddField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneycash.Marca'),
        ),
        migrations.AddField(
            model_name='documento',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_bodega', to='moneycash.Sucursal'),
        ),
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_cliente', to='moneycash.SocioComercial'),
        ),
        migrations.AddField(
            model_name='documento',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_moneda', to='moneycash.Moneda'),
        ),
        migrations.AddField(
            model_name='documento',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_periodo', to='moneycash.Periodo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_proveedor', to='moneycash.SocioComercial'),
        ),
        migrations.AddField(
            model_name='documento',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_sucursal', to='moneycash.Sucursal'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipodoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_tipodoc', to='moneycash.TipoDoc'),
        ),
        migrations.AddField(
            model_name='documento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneycash_documento_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuenta_periodo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.Periodo'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneycash.Sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='numeracion',
            unique_together=set([('tipodoc', 'sucursal')]),
        ),
    ]
