# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneycash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_administrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario', to='moneycash.Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=255, null=True, verbose_name=b'direccion de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name=b'correo electronico'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_ruc',
            field=models.CharField(max_length=14, null=True, verbose_name=b'registro unico del contribuidor (RUC)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=255, null=True, verbose_name=b'nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=14, null=True, verbose_name=b'numero de telefono'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='web',
            field=models.CharField(max_length=14, null=True, verbose_name=b'sitio web'),
        ),
    ]
